[libraries]
ktlint-cli = { module = 'com.pinterest.ktlint:ktlint-cli', version = '1.5.0' }

ktlint-maven = { module = 'com.github.gantsign.maven:ktlint-maven-plugin', version = '3.2.0' }

[plugins]
ktlint-gradle = { id = 'org.jlleitschuh.gradle.ktlint', version = '12.1.2' }
