[libraries]
kotlin = { module = 'org.jetbrains.kotlin:kotlin-bom', version = '2.4.20' }

mockito-kotlin = { module = 'org.mockito.kotlin:mockito-kotlin', version = '6.3.0' }

kotlinx-coroutines-core = { module = 'org.jetbrains.kotlinx:kotlinx-coroutines-core' }
kotlinx-coroutines-reactor = { module = 'org.jetbrains.kotlinx:kotlinx-coroutines-reactor' }
kotlinx-coroutines-debug = { module = 'org.jetbrains.kotlinx:kotlinx-coroutines-debug' }
kotlinx-coroutines-test = { module = 'org.jetbrains.kotlinx:kotlinx-coroutines-test' }
reactor-kotlin-extensions = { module = 'io.projectreactor.kotlin:reactor-kotlin-extensions' }
