name: Copyright Update
on:
    schedule:
        - cron: '0 0 31 12 *' # Repeats December 31st every year

permissions:
    contents: read

jobs:
    build:
        permissions:
            contents: write # for peter-evans/create-pull-request to create branch
            pull-requests: write # for peter-evans/create-pull-request to create a PR
        name: copyright update
        if: github.repository == 'jhipster/jhipster-kotlin'
        runs-on: ubuntu-latest
        timeout-minutes: 40
        steps:
            # Checkout
            - uses: actions/checkout@v4
              with:
                  ref: main
                  fetch-depth: 0
            # Update the copyright headers
            - name: Find and Replace
              run: |
                  CURRENT_YEAR=$(date +'%Y')
                  NEW_YEAR=$(($CURRENT_YEAR + 1))
                  grep -rlZE "Copyright ([0-9]+)-$CURRENT_YEAR" . | xargs -0 sed -i -E "s/Copyright ([0-9]+)-$CURRENT_YEAR/Copyright \1-$NEW_YEAR/g"
            # Create PR
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v6
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: 'Update copyright headers'
                  title: 'Update Copyright Headers'
                  body: 'This is an automated pull request to update the copyright headers'
                  branch: 'copyright-date-update'
                  author: 'jhipster-bot <jhipster-bot@users.noreply.github.com>'
