name: Generator
concurrency:
    # Group PRs by head_ref, push to main branch by commit id, and others branch by ref.
    group: ${{ github.workflow }}-${{ github.head_ref || (github.ref == 'refs/heads/main' && github.sha) || github.ref }}
    cancel-in-progress: true
on: [push, pull_request]
permissions:
    contents: read
jobs:
    check-npm-test:
        name: npm-test
        runs-on: ubuntu-latest
        timeout-minutes: 20
        steps:
            - uses: actions/checkout@v7
            - uses: actions/setup-node@v7
              with:
                  node-version: 24
                  cache: 'npm'
            - run: npm ci
            - run: npm run test
